import { getToken, getOrigin } from "./config.js";
import { runPublish } from "./publish.js";
import { formatAccepted } from "./echo.js";
import { listDrafts, updateDraft, deleteDraft } from "./drafts.js";
import { submitRerecord, formatRerecord } from "./rerecord.js";
import {
  AI_TOOL_IDS, CONTENT_TYPES, TARGET_DEVICE_SCHEMA, DEMO_SCRIPT_SCHEMA,
  PUBLISH_DESCRIPTION, PUBLISH_INPUT_SCHEMA,
} from "./schema.js";

// `nookframe mcp` — MCP stdio 서버. 클로드 데스크탑·커서 등 MCP 호스트가
// `npx -y nookframe mcp` 로 띄우고, 그 안의 AI가 publish_to_nookframe 툴을 호출한다.
// SDK는 optionalDependency라 동적 import — 없으면 친절히 안내.
// 발행 payload의 필드·규칙 설명은 schema.js 한 곳 — `nookframe schema`와 같은 출처다.
export async function runMcp() {
  let Server, StdioServerTransport, ListToolsRequestSchema, CallToolRequestSchema;
  try {
    ({ Server } = await import("@modelcontextprotocol/sdk/server/index.js"));
    ({ StdioServerTransport } = await import("@modelcontextprotocol/sdk/server/stdio.js"));
    ({ ListToolsRequestSchema, CallToolRequestSchema } = await import("@modelcontextprotocol/sdk/types.js"));
  } catch {
    console.error(
      "Could not load the MCP SDK. Install it with `npm i @modelcontextprotocol/sdk`, or run `npx -y nookframe mcp` instead.",
    );
    process.exit(1);
    return;
  }

  const server = new Server(
    { name: "nookframe", version: "0.1.0" },
    { capabilities: { tools: {} } },
  );

  const TOOL = {
    name: "publish_to_nookframe",
    description: PUBLISH_DESCRIPTION,
    inputSchema: PUBLISH_INPUT_SCHEMA,
  };

  // 초안 관리(요청4) — 전부 초안(is_draft) 한정. 공개된 프로젝트는 서버가 409로 거부.
  const DRAFT_TOOLS = [
    {
      name: "list_nookframe_drafts",
      description:
        "List my Nookframe drafts (not yet published). Published projects do not appear.",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "update_nookframe_draft",
      description:
        "Edit a Nookframe draft's metadata (title/description/builderNote/demoHighlights/demoScript/tags/contentType/targetDevice/demoAccess). Only the fields you send change. This tool cannot swap the URL or the files — call publish_to_nookframe again with the same URL and that draft is updated. Published projects cannot be edited.",
      inputSchema: {
        type: "object",
        properties: {
          id: { type: "string", description: "Draft id (find it with list_nookframe_drafts)" },
          title: { type: "string" },
          description: { type: "string" },
          builderNote: { type: "string" },
          demoHighlights: { type: "string" },
          demoScript: { type: "object", description: "Demo script — same shape as publish_to_nookframe's demoScript { steps, skip?, prep? }" },
          tags: { type: "array", items: { type: "string", enum: AI_TOOL_IDS } },
          contentType: {
            type: "string",
            enum: CONTENT_TYPES,
          },
          targetDevice: TARGET_DEVICE_SCHEMA,
          demoAccess: {
            type: "object",
            properties: {
              url: { type: "string" },
              params: { type: "object", additionalProperties: { type: "string" } },
              note: { type: "string" },
              impossible: { type: "boolean" },
            },
          },
        },
        required: ["id"],
      },
    },
    {
      name: "delete_nookframe_draft",
      description:
        "Delete a Nookframe draft (uploaded files included). Published projects cannot be deleted with this tool. Use it only when the user asked for the deletion, or for a draft uploaded by mistake.",
      inputSchema: {
        type: "object",
        properties: { id: { type: "string", description: "Draft id (find it with list_nookframe_drafts)" } },
        required: ["id"],
      },
    },
  ];

  // 재촬영(2026-08-26) — 공개된 작품에도 쓸 수 있는 유일한 툴이다. 그래도 공개
  // 데이터는 안 바뀐다: 새 대본은 대기 상태로 들어가고 주인이 눌러야 승격된다.
  const RERECORD_TOOL = {
    name: "rerecord_nookframe_demo",
    description:
      "Submit a rewritten demo script when the owner is unhappy with an already-published Nookframe work's demo video. Use it when you were handed the prompt the owner generated by pressing [Request re-record] on Nookframe — that prompt contains the project id, the full script currently in place, and the owner's own complaint, so leave the steps that are fine and fix only what was called out. Important: submitting does NOT change the video. The new script is stored in a PENDING slot, and filming starts only after the owner reviews it in the dashboard and presses [Re-record] — you must say this when you report back to the human. The script gate is the same as publishing (at least 4 steps, of which 3 or more carry both an action and a selector).",
    inputSchema: {
      type: "object",
      properties: {
        id: { type: "string", description: "Project id — it is written in the re-record prompt the owner gave you" },
        demoScript: DEMO_SCRIPT_SCHEMA,
        note: { type: "string", description: "One line on what changed and why (the owner reads this in the dashboard to decide, max 1000 chars)" },
      },
      required: ["id", "demoScript"],
    },
  };

  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: [TOOL, RERECORD_TOOL, ...DRAFT_TOOLS],
  }));

  server.setRequestHandler(CallToolRequestSchema, async (req) => {
    const a = req.params.arguments || {};
    const conn = { token: getToken(), origin: getOrigin() };
    try {
      switch (req.params.name) {
        case "publish_to_nookframe": {
          const { dir, screenshot, video, ...payload } = a;
          const body = await runPublish({
            payload,
            dir: dir || null,
            screenshotPath: screenshot || null,
            videoPath: video || null,
            ...conn,
          });
          const verb = body.upserted ? "Updated the existing draft" : "Uploaded as a draft";
          // 저장 에코를 툴 결과에 실어야 호출한 AI가 자기 payload가 어디까지
          // 살아남았는지(태그 철자·분류·500자 절단) 스스로 확인하고 고칠 수 있다.
          const echo = formatAccepted(body.accepted);
          return { content: [{ type: "text", text:
            `${verb} on Nookframe. Review and publish: ${body.reviewUrl}${echo.length ? `\n${echo.join("\n")}` : ""}` }] };
        }
        case "list_nookframe_drafts": {
          const { drafts } = await listDrafts(conn);
          if (!drafts?.length) return { content: [{ type: "text", text: "No drafts." }] };
          const lines = drafts.map((d) => `- ${d.id} · ${d.title}${d.demo_url ? ` · ${d.demo_url}` : ""}`
            + ` · [${d.tags?.length ? d.tags.join(", ") : "no AI tools"} / ${d.content_type || "no type"} / ${d.target_device || "screen not answered"}]`);
          return { content: [{ type: "text", text: `${drafts.length} draft(s):\n${lines.join("\n")}` }] };
        }
        case "update_nookframe_draft": {
          const { id, ...payload } = a;
          const body = await updateDraft(id, payload, conn);
          const echo2 = formatAccepted(body.accepted);
          return { content: [{ type: "text", text:
            `Draft updated. Review: ${body.reviewUrl}${echo2.length ? `\n${echo2.join("\n")}` : ""}` }] };
        }
        case "rerecord_nookframe_demo": {
          const { id, ...body } = a;
          const res = await submitRerecord(id, body, conn);
          return { content: [{ type: "text", text: formatRerecord(res).join("\n") }] };
        }
        case "delete_nookframe_draft": {
          await deleteDraft(a.id, conn);
          return { content: [{ type: "text", text: "Draft deleted (uploaded files included)." }] };
        }
        default:
          return { isError: true, content: [{ type: "text", text: `Unknown tool: ${req.params.name}` }] };
      }
    } catch (err) {
      return { isError: true, content: [{ type: "text", text: `Failed: ${err instanceof Error ? err.message : String(err)}` }] };
    }
  });

  await server.connect(new StdioServerTransport());
  // stdio 서버는 연결 후 표준입출력으로 계속 통신 — 프로세스가 종료되지 않게 유지된다.
}
